### ISSUE TITLE
Emoticons fail

### ISSUE THREAD

**Issue by powtac** [un33k/python-slugify#10]

**Comment by un33k** [comment]
no description, so it must be spam.

**Comment by powtac** [comment]
Hi @un33k, is the conversion of emoticons supported by python-slugify ?

**Comment by un33k** [comment]
Oh, I see. The answer is no. but it would be a cool feature if you have a pull request.

**Comment by powtac** [comment]
Sorry, I don't have a PR. I was researching on different slugify libraries and facing this emoticons problem :confused:

**Comment by un33k** [comment]
@powtac Could you provide a use-case. The string of some sort?

**Comment by powtac** [comment]
A test string like this: `abc🎅`. Should maybe output like this `aaa`

**Comment by un33k** [comment]
I'll have it in mind during the next release cycle.
