### ISSUE TITLE
Empty slug for emojis

### ISSUE THREAD

**Issue by ShubhamKhandare** [un33k/python-slugify#105]
```python
In [1]: from slugify import slugify

In [2]: slugify('રાજમાં')
Out[2]: 'raajmaan'

In [3]: slugify('好こん안tวั')
Out[3]: 'hao-konantwa'

In [4]: slugify('😀 😃 😄 😁 😆 😅 😂 🤣 🥲 ☺️ 😊 😇 🙂 🙃 😉')
Out[4]: ''
```

For emojis and other special characters, the slug is coming empty.

**Comment by un33k** [comment]
@ShubhamKhandare If the underlaying libraries don't support emojis, the slug will be empty. 

Depending on the package you use, you may want to raise the ticket with one of the following supported packages. 

`text_unidecode` OR `unidecode`.
