### ISSUE TITLE
Question/Bug: how do I preserve dashes and not replace them with separator?

### ISSUE THREAD

**Issue by adamcunnington-mlg** [un33k/python-slugify#107]
I am trying to slugify a string, replacing non-matching characters with an underscore, but I don't want to consider a dash a non-matching character. This is easily achieved with regex but it looks like there is some special slugify behaviour when it comes to dashes which is preventing this working. I can't see anything in the docs or code, about how to work around this.

**What did I do?**
```python
slugify.slugify("test-foo bar", separator='_', regex_pattern=r'[^-a-zA-Z0-9_]+')
```

**What happened?**
`test_foo_bar`

**What did I expect?**
`test-foo_bar`

**Comment by adamcunnington-mlg** [comment]
Pretty sure it is a big, caused by https://github.com/un33k/python-slugify/blob/master/slugify/slugify.py#L179

Looks like there is a test case missing.

**Comment by adamcunnington-mlg** [comment]
@un33k

**Comment by un33k** [comment]
Please note that '-' is a reserved character in slugs.  This package allows an atomic replacement of the default separator of '-' with something else towards the end of the process.

A simple preprocess of the text is recommended for special cases.

**Comment by adamcunnington-mlg** [comment]
Ok, I think this is definitely PR-worthy. I agree that '-' is a reserved character - but this is precisely the reason why you shouldn't remove them. I can pre-process the string; sure; but this seems a bit broken.

Will find time to raise PR.

**Comment by adamcunnington-mlg** [comment]
Also, there's a logical problem with the suggested workaround. Pre-processing the string is highly problematic - what character am I going to replace - with, before I pass it to a call to slugify that is going to replace characters that don't match my regex? I have a very limited set of options and whatever I choose could legitimately appear elsewhere in the string and be erroneously substituted by the post-processing.

The only thing I could do is replace - with some string that i think is going to be reasonably unique. This is brittle and bad. This behaviour should belong to slugify.

**Comment by un33k** [comment]
Just use something like this and move on delivering your software.  https://github.com/un33k/python-slugify/blob/a90d96778a004a9f2fdc232debcd72fdb5bbf085/test.py#L94

**Comment by un33k** [comment]
Closing this now, feel free to reopen if the above example is not addressing your needs and/or you have a PR.

**Comment by PradeepTammali** [comment]
I am facing the same issue here. I have a text like this `121232-some text here-some text here again` 
Trying to `slugify` the text with separator `' '`. Expecting the output `121232-some text here-some text here again` but got `121232 some text here some text here again` 

Is there any work around for this.

**Comment by un33k** [comment]
@PradeepTammali Slugify needs one reserved character, and since the name of the package is `slugify` its job is to clean text to `dash`-delimited clean text for use in URLs.  With that said, the delimiter can also be changed to whatever user wants.  With that said, the `ask` here is not doable.  Someday you may want channel your energy to raising a meaningful PR instead.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

Global dash-to-separator mapping remains unchanged. No new literal-hyphen-preservation API is introduced; modern length budgeting does not resolve that separate request.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
