### ISSUE TITLE
Syntax error in slugify/slugify.py 

### ISSUE THREAD

**Issue by janderson-atb-potsdam** [un33k/python-slugify#110]
Hello,

The current master branch (commit c096bcdd76b0ef216716eccef5b19839266e1372)
gives a syntax error in slugify/slugify.py 

  File ".../site-packages/slugify/slugify.py", line 69
    replacements: typing.Iterable[typing.Iterable[str]] = ()):
                ^
SyntaxError: invalid syntax

Have a good day

**Comment by un33k** [comment]
Could you indicate the python version you are using ? 

@mrezzamoradi could you tract this issue?  `typing` was introduced during the last PR.

**Comment by mrezzamoradi** [comment]
@un33k This change was added before the last PR [in this commit](https://github.com/un33k/python-slugify/commit/1097c2366ffcb4356ba84f74c7daf42bcfe720bf). Still, it should be fine with Python >= 3.6
What version of Python are you using @janderson-atb-potsdam ?

**Comment by janderson-atb-potsdam** [comment]
Python 2.7

Perhaps you could put in a check that the Python version meets the minimum requirement when the slugify module is imported?

Sorry for wasting your time on something like this.  I am trying to install a docker container on a server, and it looks like something inside of that is pulling the most recent version of slugify, even though it is still running Python 2.7.  I will try to trace this back up the chain and file a bug report to the package repository that does this.

**Comment by mrezzamoradi** [comment]
@janderson-atb-potsdam it's fine, don't worry about our time.
@un33k we can remove this type hinting and improve the docstring if we want to keep supporting python 2. what do you think?

**Comment by un33k** [comment]
@mrezzamoradi It seems that may projects are using the latest version without pinning down the specific version.

I agree, that we improve the docstring for now, and remove the type hinting. At some point we will do a major release and bring types back.

Here is another related issue for your ref: https://github.com/un33k/python-slugify/issues/112.

Please kindly go ahead with your recommendation.
