### ISSUE TITLE
Missing slugify cmd line command: removed 'entry_points' from setup.py

### ISSUE THREAD

**Issue by reixd** [un33k/python-slugify#114]
Hello @un33k,

my CI scripts started failing after updating to the latest version v6.1.1 .
Digging further I noticed, that you removed the 'entry_points' from setup.py (See https://github.com/un33k/python-slugify/commit/7534199cf4b214309619e7486e1de1057bff74a3#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L70 )
Was this on purpose?

Using only the cmd line command it's very useful.

If necessary I can provide a PR myself.

With regards,

reixd

**Comment by un33k** [comment]
We removed it to contain the package as a pure python package.

Not sure what you use command line in CI/CD.

If you want it back, raise a PR, 60/40 it will go in.

Thanks,

**Comment by reixd** [comment]
I will give it a try and come back later with a proposition.

**Comment by skycaptain** [comment]
Same issue. `python3 -m slugify` can be used as a workaround, however the [examples](https://github.com/un33k/python-slugify#command-line-options) from the README do not work anymore:

```
$ python3 -m pip install python-slugify
...
$ echo "Taking input from STDIN" | slugify --stdin
bash: slugify: command not found
```

**Comment by un33k** [comment]
command line is reintroduced as part of 6.1.2.
