### ISSUE TITLE
Installing python-slugify on Python 2.7 does not install a compatible version of slugify

### ISSUE THREAD

**Issue by ndelon** [un33k/python-slugify#115]
Hello,

It seems that since python-slugify 6.0.0 has been released, the appropriate version of slugify is no longer installed when using Python 2.7.

Back in 5.0.2, the `python_requires` argument of `setup.py` was set to `>=3.6`, meaning that this version was not eligible for Python 2.7 and that pip would have automatically installed slugify 4.0.1 (where the `python_requires` expression fits Python 2.7) as expected.

Since 6.x, `python_requires` has been set to `">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*"` meaning that this version is installed by pip on Python 2.7 (instead of slugify 4.0.1) and cannot work.

It could be fixed, but I think that if it is fixed (for instance) in a future 6.1.3 version, then pip on Python 2.7 will simply install the 6.1.2 version instead and the initial issue will remain.

When developing a library that uses slugify and that still supports Python 2.7, the version dependency has to be set explicitly like I did here: https://github.com/lemoncheesecake/lemoncheesecake/blob/09f4bd84b53f599d52c9749bebbe078e6e1d5f15/setup.py#L15

Best regards,

Nicolas.

**Comment by kurtmckee** [comment]
Agreed, this is strange. All versions of python-slugify that have been released with Python 2.7 support reintroduced need to be yanked from PyPI.

Commit 7534199cf4b214309619e7486e1de1057bff74a3 introduced this problem.

**Comment by ndelon** [comment]
I'm not sure to understand: you want to remove impacted versions of python-slugify from PyPI ?

**Comment by kurtmckee** [comment]
Yes, yanking is the correct way to handle this situation.

The project owners will have to make a decision how to proceed with new versions or replacements, but unless the affected versions are yanked from PyPI then Python 2.7 users will continue to pick up the new version.

**Comment by ndelon** [comment]
I think it is a **very dangerous** thing to do: it will break any project's build process that uses a pinned version of python-slugify.

As I explained previously, I don't think there is much to do here except:
- fixing `setup.py`
- and documenting how to install python-slugify on Python 2.7 (i.e `pip install python-slugify~=4.0.1`)

This is a very minor issue anyway since:
- Python 2.7 is deprecated for more than 2 years and is no longer widely used
- the regression has been introduced in 6.0.0 released in February 16 and it seems that I am the first one to raise the issue

**Comment by un33k** [comment]
It is a good time to drop P2. Let's do it.

**Comment by un33k** [comment]
2.7-3.6 inclusively were dropped in version 7.0.0.
