### ISSUE TITLE
Proposal: Discontinue Python 2 support

### ISSUE THREAD

**Issue by jdevera** [un33k/python-slugify#117]
I want to propose dropping support for Python 2. The library is pretty stable as is, and there are barely any open bugs, so any [remaining python 2 users](https://pypistats.org/packages/python-slugify) can continue to use the current version.

**Comment by un33k** [comment]
To drop P2, we have to release a new major version.  As per SemVer, we need to do that if we introduce backward incompatibility, which we are in a way.
