### ISSUE TITLE
Document the use of what's in special.py

### ISSUE THREAD

**Issue by jdevera** [un33k/python-slugify#120]

**Comment by un33k** [comment]
Sounds good.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

Exported substitution tables and an explicit German pre-replacement recipe are documented. Tables are optional, not automatic locale detection.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
