### ISSUE TITLE
How to replace the ampersand symbol "&" for two hyphens "--"?

### ISSUE THREAD

**Issue by rafaelmarino** [un33k/python-slugify#123]
Hi, I have a list of job titles I need to slugify, as part of the requirements I need to convert ampersands ("&") into double hyphens ("--"). I am able to successfully replace the ampersand for any other symbol/group of symbols except for double (and I suspect multiple) hyphens. Any workaround for this?

```python
job_title: str = "ENGINEER - LEVEL II/III & SENIOR"
target: str = "engineer-level-iiiii--senior"
slugg: str = slugify(job_title, replacements=[["&", "--"], ["/", ""]])
print(slugg)  # engineer-level-iiiii-senior
assert target == slugg  # AssertionError
```

**Comment by un33k** [comment]
Too many combinations and permutations out there. 
You'd need to pre+post process the job title.
Use `slugify` for one thing, and that is to convert your string to a slug.

Do something like this:
```python
job_title: str = "ENGINEER - LEVEL II/III & SENIOR"
# convert  `&` to something very unique. (e.g "vvvvvvv")
job_title = job_title.replace("&", "vvvvvvv")
# slugify the job title (res: "engineer-level-ii-iii-vvvvvvv-senior")
slug = slugify(job_title)
# finalize your slugged job title (out: "engineer-level-ii-iii--senior")
job_title = slug.replace("-vvvvvvv-", "--")
```

Any follow up should go to stackoverflow please.
