### ISSUE TITLE
Fuzzing Python Slugify on OSS-Fuzz

### ISSUE THREAD

**Issue by rikfie** [un33k/python-slugify#127]
Hi there, 

Are you interested to get Python Slugify fuzzed*? I have written [a harness for Python Slugify](https://github.com/rikfie/python-slugify-fuzzer) and it's ready to be integrated. Many libraries are being fuzzed on [OSS-Fuzz ](https://github.com/google/oss-fuzz)on a daily basis and I would like to add Python Slugify. 

The only condition for fuzzing on OSS-Fuzz is that any bugs found must be fixed and released within 90 days; the bug will be publicly disclosed past this point.

If you're interested, please provide me with an e-mail address of a maintainer. The e-mail address must be linked to a Google account. Note that the addresses will be stored in a public repository. If this is not an option, I can forward bug reports to you. Although I can propose for the integration of Python Slugify to OSS-Fuzz, the decision is up to OSS-Fuzz.

\* Fuzz testing is a well-known technique for uncovering programming errors in software. OSS-Fuzz aims to make common open source software more secure and stable by combining modern fuzzing techniques with scalable, distributed execution.

**Comment by un33k** [comment]
No plan of action at the moment.  Thx

**Comment by rikfie** [comment]
Ok fair enough.  Feel free to close it.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

Bounded combinatorial regression coverage is added. OSS-Fuzz enrollment and a separate disclosure-response program are NOT implemented by #191.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
