### ISSUE TITLE
Enable installation without GPL dependencies

### ISSUE THREAD

**Issue by C-nit** [un33k/python-slugify#128]
#126 enabled the use of `Unidecode` as alternative to to `text-unidecode`. However it would be nice if there was an alternative to avoid installing GPL dependencies.

As a first step it would be great if one could call `slugify` with `allow_unicode=True` that works without any of the GPL dependencies installed.

**Comment by un33k** [comment]
There are no GPL dependencies.  Unidecode author: "using the API creates no dependencies".  We've included two ways of installing it.  Whichever way we choose to go first, some people object. Hence no more license-related changes.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

Dependency-free normal installation remains deferred: text-unidecode is still a base dependency. Lazy loading permits Unicode-only runtime without a backend, but does not remove installation metadata requirements or provide a blanket licensing assurance.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
