### ISSUE TITLE
pip install python-slugify[unidecode] also installs text-unidecode

### ISSUE THREAD

**Issue by Schulzjo** [un33k/python-slugify#140]
Hey,
`pip install python-slugify[unidecode] ` also installs text-unidecode.
Do I misunderstand the notice on the README? 
I have interpreted the note in such a way that it installs unidecode as alternative and not parallel.

Thx for clarification

**Comment by un33k** [comment]
text-unidecode is default, unidecode is extra. 

if unidecode is found, text-unidecode will be ignored, but not uninstalled.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

Documentation clarifies additive extras, installed dependencies and runtime backend selection. Selecting a backend does not subtract the base dependency.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
