### ISSUE TITLE
Unicode confusables characters are removed

### ISSUE THREAD

**Issue by chuckyblack** [un33k/python-slugify#142]
https://util.unicode.org/UnicodeJsps/confusables.jsp?a=a&r=None

### Current result

```python
from slugify import slugify

assert slugify("𝐚́́𝕒́") == ""
```

### Expected result

```python
from slugify import slugify

assert slugify("𝐚́́𝕒́") == "aa"
```

### Possible solution

I think `text = unicodedata.normalize("NFKC", text)` should be called before `text = unidecode.unidecode(text)`.

**Comment by un33k** [comment]
@chuckyblack  thanks for reporting it.  I have raised a PR, which will normalize the text twice. 

https://github.com/un33k/python-slugify/pull/143
