### ISSUE TITLE
TypeError: decoding to str: need a bytes-like object, int found

### ISSUE THREAD

**Issue by codyc1515** [un33k/python-slugify#144]
There is [code present](https://github.com/un33k/python-slugify/blame/e52c35e34899bc21a389aa7f4fe5084423cf538c/slugify/slugify.py#L116) to convert any non-Str values passed in into Str; however, I don't think this part of the code can ever be reached. Example:

```
>>> from slugify import slugify
>>> slugify(123)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\CodyC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\slugify\slugify.py", line 95, in slugify
    text = str(text, 'utf-8', 'ignore')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: decoding to str: need a bytes-like object, int found
```

```
>>> slugify('123')
'123'
```

**Comment by un33k** [comment]
Ah, the good old days when this module lacked typings and supported both Python 2.7 and 3+. Now, with the typing of text: str, it's required that the caller passes in a string.

Some parts of the code might need pruning; however, the module is very stable. Rocking the boat is not part of the plan moving forward. Thanks.

**Comment by codyc1515** [comment]
No problem. It seems like this module always fails if passed a non-Str, so I think we can remove that code then?

**Comment by un33k** [comment]
Next time around ..

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

Unsupported input types receive a clear TypeError; UTF-8 bytes and bytearray remain supported.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
