### ISSUE TITLE
Argument to make flugified strings valid XML id attributes.

### ISSUE THREAD

**Issue by jenstroeger** [un33k/python-slugify#150]
Thank you for this great package! I have a question/feature request, though.

Suppose I have a call like this:
```python
>>> slugify.slugify("1: Into the Dark")
'1-into-the-dark'
```
which is an invalid XML `id` attribute because it starts with a number (see also [`xml:id` spec](https://www.w3.org/TR/xml-id/) and [NCName](https://www.w3.org/TR/xml-names11/#NT-NCName) definition).

Would it make sense to add a `valid_xml_id=True` argument to the `slugify()` function? My current approach is somewhat naive:
```python
slug = slugify.slugify(chapter_title, max_length=32)
if regex.fullmatch(r"^\d+.*", slug):
    slug = f"chapter-{slug}"
```
but I think having support from `slugify()` might benefit others, too? Happy to attempt a PR, if it helps.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

An XML-specific slug option is not adopted. XML identifier validation and any required prefixing remain caller responsibilities.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
