### ISSUE TITLE
Unicode does not work

### ISSUE THREAD

**Issue by pomponchik** [un33k/python-slugify#151]
Hello!

I try your library with this code:

```python
>>> from slugify import slugify
>>> text = 'Это против природы, это неестественно'
>>> slugify(text)
```

When i running this code, i get an exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path_to_the_project/venv/lib/python3.7/site-packages/slugify.py", line 24, in slugify
    unicode(
NameError: name 'unicode' is not defined
```

I use Python 3.7.7 on MacOS darwin.

**Comment by un33k** [comment]
All python version have passed their tests. 
Including 3.7 as per: https://github.com/un33k/python-slugify/actions/runs/8115538091


It is possible that you are running another package called slugify.

Please do:

$ pip uninstall slugify
$ pip uninstall python-slugify
$ pip install python-slugify

And try again.

$ python --version
Python 3.11.4

>>> from slugify import slugify
>>> text = 'Это против природы, это неестественно'
>>> slugify(text, allow_unicode=True)
'это-против-природы-это-неестественно'
