### ISSUE TITLE
The problem of converting all Korean consonants to Korean initials in the slugfiy process when they are alone.

### ISSUE THREAD

**Issue by LMouSoo** [un33k/python-slugify#153]
카커쿠 <- combined form of Korean consonant and vowel
ㅋㅏㅋㅓㅋㅜ<- sepearated form of Korean consonant and vowel
if they're seperated, unicode value of each symbol will be differentiated
 
It doesn't happen often, but just like abbreviations like ASAP in English, Korean often uses consonant-only abbreviations.
For example, ㅋㅋㅋ is used similarly to lol and ㅜㅜ is used similarly to ;_; (sad emoji)

If you type ㅋ in a web address by itself, without combining it with any other consonants, it should be interpreted as Unicode 12619. However, when run it through python slugify, it changes to Unicode 4367. Is there any way to avoid this problem?

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

Normalization/jamo behavior is documented and regression-covered. Exact original code-point preservation is not implemented.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
