### ISSUE TITLE
Support only sanitizing URL without stripping unicode?

### ISSUE THREAD

**Issue by jeffwidman** [un33k/python-slugify#24]
I'd like to use this library for sanitizing the URL by stripping out non-letters, converting spaces to dashes, etc. 

But I don't want to convert non-english letters to their ASCII equivalents. For example, I want `slugify('ß')` to return 'ß'. Could you add a parameter that supports this behavior? 

Similar to the default behavior of this library? https://github.com/mozilla/unicode-slugify

I want the extra options of `python-slugify` such as max length, word boundary, stopwords, and an active maintainer, otherwise I'd use that library.

**Comment by un33k** [comment]
No plan for such feature at this moment.  Such a pull requests from community will be considered for sure.
