### ISSUE TITLE
\u2019 should be replaced by a separator

### ISSUE THREAD

**Issue by cosmicyom** [un33k/python-slugify#30]
The right single quotation mark (`’`) should be replaced by a separator, like the standard apostrophe.

Maybe `\u2019` should be searched in `QUOTE_PATTERN` ?

More info : [Response to "What’s the right character for an apostrophe?"](http://graphicdesign.stackexchange.com/a/66812/78704)

**Comment by un33k** [comment]
No perfect solution here. I welcome a pull request that doesn't break the current behavior and makes everyone happy and comes with proper test cases.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

A global curly-apostrophe behavior change is not adopted. ASCII and curly apostrophes remain distinct; callers can choose explicit pre replacements.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
