### ISSUE TITLE
I can't start slugify from the command-line

### ISSUE THREAD

**Issue by sodre** [un33k/python-slugify#41]
Hi, 
I can call slugify from the command line after installing your package. Would you be okay moving the main function into the module slugify.cli ?

Thanks!

**Comment by un33k** [comment]
@sodre Send me a PR ... with your fix?

**Comment by sodre** [comment]
I will propose one tonight.

**Comment by sodre** [comment]
Closing this since I can't get it to replicate outside a conda-build cycle.
