### ISSUE TITLE
Slugifying Chinese characters with multiple readings

### ISSUE THREAD

**Issue by imrek** [un33k/python-slugify#44]
This is probably beyond doable, since it would require extensive lookups, but slugifying can result in erroneous output if a given character has multiple readings (多音字), and context would be required to determine the correct slug, e.g. 行 is correctly rendered 'xing' when it stands alone, but 'hang' it would have to be slugified as 'hang' when it stands with 银行 (銀行) in a compound word. (See [3rd paragraph in this](https://en.wikipedia.org/wiki/Chinese_characters#Function).)

**Comment by un33k** [comment]
The conversion is done by the underlaying modules.
