### ISSUE TITLE
Slugifying Danish, Norwegian, German

### ISSUE THREAD

**Issue by imrek** [un33k/python-slugify#45]
I may have misunderstood the original intentions of this module, but some German, Danish/Norwegian letters aren't mapped correctly by `slugify`. E.g. while  'æ' is correctly resolved as 'ae' (Danish/Norwegian), 'ø' is incorrectly rendered 'o' (in Danish only, but correct for Norwegian usage). The mapping of 'ö' is also language dependent (German: 'oe', but Hungarian, Finnish, Swedish: 'o')

**Comment by un33k** [comment]
The conversion is done by the underlaying modules.

**Comment by imrek** [comment]
That's all right, if real world usage doesn't matter. Thanks.
