### ISSUE TITLE
Possible license conflict with Unidecode?

### ISSUE THREAD

**Issue by NiklasMM** [un33k/python-slugify#49]
I just noticed, that Unidecode is licensed under the GPL, while python-slugify uses the MIT license.

The way I understand things, this is not possible since any code using the API of a GPL licensed piece of software must also be releases under the terms of the GPL.

**Comment by un33k** [comment]
no issue - https://github.com/un33k/python-slugify/issues/7

**Comment by un33k** [comment]
@NiklasMM Please note that version 2.0.0 always prefers Unidecode however, it gracefully falls back on text-unidecode if it is already installed. (Just an FYI)
