### ISSUE TITLE
License incompatibility due to unidecode being GPLv3

### ISSUE THREAD

**Issue by bolkedebruin** [un33k/python-slugify#50]
Hi There,

I am one of the maintainers of Apache Airflow, licensed under the Apache License 2.0. A contributor made us aware that we are dependent on “unidecode” a GPLv3 licensed python library, due to an indirect dependency on python-slugify (by means of python-nvd3).

As derivative works of GPLv3 also need to GPL licensed this would make also python-slugify incompliant due to its MIT license. I have asked the maintainer of “unidecode” to dual license under the perl artistic license which would be compatible, but unfortunately that was refused (https://github.com/avian2/unidecode/issues/23). 

As python-slugify therefore seems to have a license incompatibility issue, would you accept a patch that changes the dependency to text-unidecode (https://github.com/kmike/text-unidecode)?

Thanks
Bolke

**Comment by un33k** [comment]
This has come up many [times](https://github.com/un33k/python-slugify/issues/7) before.

> Derivative

Using a set of APIs from a module is not equal to being derived from that module.

API dependancy does NOT mean licensing dependency.  If your open source application with MIT license runs on Linux and uses their APIs, it doesn't have to be licensed as GPL or LGPL.

[FYI](https://en.wikipedia.org/wiki/Derivative_work)

Use without concern.

**Comment by bolkedebruin** [comment]
Sorry to have missed that. I will verify with Apache Legal if they think the same way. Cheers

**Comment by bolkedebruin** [comment]
@un33k for future reference and what it is worth the author of unidecode agrees with you: https://github.com/avian2/unidecode/issues/23#issuecomment-360725623

**Comment by un33k** [comment]
@bolkedebruin Please note that version 2.0.0 always prefers Unidecode however, it gracefully falls back on text-unidecode if it is already installed. (Just an FYI)
