### ISSUE TITLE
GPL actually?

### ISSUE THREAD

**Issue by haizaar** [un33k/python-slugify#51]
Hi guys,

While this library is MIT licensed, it uses unidcode, which is GPL licensed, practically making any SW that uses slugify to comply with GPL.

Was it an intentional decision to use GPL licensed library underneath?

Thank.

**Comment by haizaar** [comment]
I see it was discussed before. Sorry for the noise.

**Comment by un33k** [comment]
@haizaar Please note that version 2.0.0 always prefers Unidecode however, it gracefully falls back on text-unidecode if it is already installed. (Just an FYI)
