### ISSUE TITLE
Conditional dependency on unidecode/text-unidecode

### ISSUE THREAD

**Issue by bolkedebruin** [un33k/python-slugify#52]
Hi,

I have reached out before to discuss the dependency on `unidecode` which for some is an issue due to `unidecode` being GPL. It was argued by you as authors of `python-slugify` and the author of `unidecode` that this is not an issue. While I _personally_ agree, I have a hard time convincing others (https://issues.apache.org/jira/browse/LEGAL-362). 

This means as a project (Apache Airflow) we are caught between a rock and hard place. The dependency is buried deep down for us and if we are really forced to remove it from our dependency tree we would need to replace some core items (ie. forking python-nvd3 and python-slugify most likely). This is obviously not what we want: we are very happy with both. So this is a call for help.

In the exchanges I had with you and the author of `unidecode` it was argued that the usage of `unidecode` by `python-slugify` is equal to the usage of an API (i.e. the same as glibc/linux kernel headers). This would mean that one should be able to replace `unidecode` by an equivalent that exposes the same API. Fortunately, there is one `text-unidecode`. 

However, the way python works makes this a bit tough. A `pip install python-slugify` (or a `pip install apache-airflow`) will always bring in `unidecode` although `text-unidecode` might be present on the system. This also makes the argument that `unidecode` is just an API weaker.

What I would like to suggest is to have a conditional dependency which would default to `unidecode`. If an environment variable called `WITH_TEXTUNIDECODE` is defined (inspired by FreeBSD's make.conf https://www.freebsd.org/cgi/man.cgi?make.conf(5)) `text_unidecode` would be used instead when installing. An alternative approach could be to make use of setup.cfg, although that seems less flexible. Both are PEP508 compatible (https://hynek.me/articles/conditional-python-dependencies/).

I volunteer to create a PR for this and to maintain it for at least a year. It would really help us getting past the hurdle that we see in https://issues.apache.org/jira/browse/LEGAL-362 . 

Thanks a lot for your consideration.

**Comment by un33k** [comment]
Please submit a PR.

**Comment by bolkedebruin** [comment]
@un33k awesome thanks for merging! would you mind doing a (minor) release to pypi?

**Comment by un33k** [comment]
1.2.5 is published. thx.

**Comment by un33k** [comment]
@bolkedebruin Please note that version 2.0.0 always prefers `Unidecode` however, it gracefully falls back on `text-unidecode` if it is already installed. (Just an FYI)
