### ISSUE TITLE
setuptools error

### ISSUE THREAD

**Issue by fabiocaccamo** [un33k/python-slugify#58]
Python 2.7

setuptools error when `pip install python-slugify==1.2.5`
ImportError: No module named pkg_resources

Running `pip install python-slugify==1.2.4` works fine.

**Comment by un33k** [comment]
@fabiocaccamo  Please check your environment as it installs just fine on a brand new 2.7 virtual env.

21:25:16 [~/py2test] [py2test] $ **python**
**Python 2.7.15** (default, Jun 17 2018, 12:46:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```>>> exit()```

**pip install python-slugify==1.2.5**
Collecting python-slugify==1.2.5
Collecting Unidecode>=0.04.16 (from python-slugify==1.2.5)
  Using cached https://files.pythonhosted.org/packages/59/ef/67085e30e8bbcdd76e2f0a4ad8151c13a2c5bce77c85f8cad6e1f16fb141/Unidecode-1.0.22-py2.py3-none-any.whl
Installing collected packages: Unidecode, python-slugify
**Successfully installed Unidecode-1.0.22 python-slugify-1.2.5**
