### ISSUE TITLE
Use the setuptools "Extras" feature to choose between Unidecode and Text-Unidecode

### ISSUE THREAD

**Issue by roniemartinez** [un33k/python-slugify#68]
Hi @un33k ,

Thanks for this library! 👍 

I would like to request an option for users to install `python-slugify` with their preferred decoders.

When using `requirements.txt`, everyone is forced to used `Unidecode` which is GPL-licensed. 
Using the "[Extras](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)" feature of setuptools would be a great help!

Example:
```
pip install python-slugify[unidecode]
pip install python-slugify[text-unidecode]
```

As a reference, this has been used by popular libraries like [Django](https://github.com/django/django/blob/master/setup.py#L87):
```
pip install django[bcrypt]
pip install django[argon2]
```

**Comment by un33k** [comment]
@roniemartinez In this ([PR](https://github.com/un33k/python-slugify/pull/63) I made a change that allows the swap of the underlying decode module.

We need at least one decoding module to be installed as they are not optional or extras.
We need to allow for `pip install python-slugify`.

If you find a way to allow the default installation, please send me a PR.
Thx

**Comment by un33k** [comment]
@roniemartinez The name `python-slugify` namespace is part of licensing. You should not make version 2,3 for an actively maintained packages.
