### ISSUE TITLE
python-slugify depends on a GPL library

### ISSUE THREAD

**Issue by sekrause** [un33k/python-slugify#7]
While `python-slugify` itself is BSD licensed its dependency Unidecode is a pure GPL library. It's technically not a problem for `python-slugify` because the licenses are compatible, but it should probably be mentioned somewhere because this makes `python-slugify` unfit for most commercial deployments.

**Comment by un33k** [comment]
@sekrause Please note that version 2.0.0 always prefers Unidecode however, it gracefully falls back on text-unidecode if it is already installed. (Just an FYI)
