### ISSUE TITLE
Name conflict with other slugify package

### ISSUE THREAD

**Issue by EmileSonneveld** [un33k/python-slugify#81]
When working on the following code:
```python
from slugify import slugify
fname = slugify("cc / loc") + ".png"
```
My IDE (PyCharm 2018.2.5) will suggest to automatically download a package, but the wrong one. And this results in an error: ```NameError: name 'unicode' is not defined```

The namespace of this package should be changed, or the half implemented package should be removed from PIP.

A tool like this should work out of the box.

**Comment by EmileSonneveld** [comment]
The problems seems that there is another package with the same name that automatically get't installed by my IDE (PyCharm 2018.2.5)
So the root of this issue would be a name conflict with that package.

**Comment by un33k** [comment]
I don't think the name-space `python-slugify` can have multiple versions on pypi.  With that said, some sadly clone the repo and publish it as `python-slugify2`, `python-slugify3` etc. If your IDE falls for the number in the name as the true `version`, then it is possible that a fake/clone version is installed by PyCharm.

You can be more specific and install it as `python-slugify[unidecode]` as per https://github.com/un33k/python-slugify#notice

**Comment by roniemartinez** [comment]
> then it is possible that a fake/clone version is installed by PyCharm

He installed the [slugify](https://pypi.org/project/slugify/) package, not `python-slugify`. It's been there 9 years ago, certainly not a clone.

https://github.com/zacharyvoase/slugify/blob/master/src/slugify.py#L24

**Comment by un33k** [comment]
@EmileSonneveld  Only you knows what you installed. Any package should install it own dependencies or fall on a default one, and provide options.  Never used pyCharm so I don't know what it does.  See what you installed and raise a ticket with that package.

**Comment by roniemartinez** [comment]
@un33k I use PyCharm. If you import a module and it does not exist yet PyCharm will ask you to install what you imported, in the case of:

`import slugify`

It will install the `slugify` package and not`python-slugify`

**Comment by un33k** [comment]
@roniemartinez then this issue needs to be posted on the slugify's page instead.

**Comment by EmileSonneveld** [comment]
I raised the issue in the conflicting library too. However, I am convinced that if this package is called `python-slugify`, the namespace in the code should reflect that. However, it is difficult to fix that while retaining backwards compatibility of course.

**Comment by un33k** [comment]
@EmileSonneveld name of a package is different than the set of api it publishes. `python-slugify` is a reserved name for pypi. Remember that importing sys in python is `import sys` and not `import python-sys`. So name of a package has nothing to do with what is inside of it.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

Install-name versus import-name troubleshooting is documented. No package namespace rename is introduced.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
