### ISSUE TITLE
German Umlaut support

### ISSUE THREAD

**Issue by TobitRE** [un33k/python-slugify#85]
It would be great if slugify support German umlaut like

`slugify_de('ÜBER Über slugify')               # UEBER-Ueber-slugify`

[awesome-slugify](https://github.com/voronind/awesome-slugify) does a great job but the development hass been stoped.

**Comment by un33k** [comment]
@TobitRE You can achieve this by pretranslation replacements. Mind you that you may be bound to lowercase slugs only. 

```python
txt = 'ÜBER Über German Umlaut'
r = slugify(txt, replacements=[['Ü', 'UE'], ['ü', 'ue']])
self.assertEqual(r, "ueber-ueber-german-umlaut")
```

Or you can pass your own replacement list.
```python
GERMAN_UMLAUT = [
    [u'ä': u'ae'],   
    [u'ö': u'oe]',   
    [ u'ü': u'ue'],  
}
txt = 'ÜBER Über German Umlaut'
r = slugify(txt, replacements=GERMAN_UMLAUT)
self.assertEqual(r, "ueber-ueber-german-umlaut")
```

Alternatively, you can 
```python 
from slugify import PRE_TRANSLATIONS
txt = 'ÜBER Über German Umlaut'
r = slugify(txt, replacements=PRE_TRANSLATIONS)
self.assertEqual(r, "ueber-ueber-german-umlaut")
```

**Comment by kennell** [comment]
^ the code example above has several syntax errors. Here is a Python3 code example for people stumbling on this issue via Google:

```python
from slugify import slugify
GERMAN_UMLAUT = [
    ['ä', 'ae'],
    ['ö', 'oe'],
    ['ü', 'ue'],
]
slugify('Baden-Württemberg', replacements=GERMAN_UMLAUT)
```
