### ISSUE TITLE
Can I be sure that slug is urlsafe?

### ISSUE THREAD

**Issue by mvolfik** [un33k/python-slugify#90]
I don't know the definition of slug, so I'd like to ask: is there some kind of guarantee (I know that the license says no guarantees and stuff, but some guarantee for normal human/developer) that the slug will be url-safe? Also this might be mentioned in the "docs" (readme)...

**Comment by un33k** [comment]
The default slugify() is url safe as it only returns ASCII characters and dashes.  But since slugify() takes many parameters, one can pass in params that makes the output, possibility unsafe for url consumption. The power is with the caller of the slugify() I'd say.
