### ISSUE TITLE
Issue with separator

### ISSUE THREAD

**Issue by m1n1m4l** [un33k/python-slugify#91]
In [2]: slugify("aaa bbb-ccc")                                                         
Out[2]: 'aaa-bbb-ccc'

In [3]: slugify("aaa bbb-ccc", separator='.')                                          
Out[3]: 'aaa.bbb.ccc'

I was expecting to get 'aaa.bbb-ccc'.

**Comment by un33k** [comment]
This package removes any non-alpha numeric characters and replaces them by the separator of your choice or '-' if you don't provide one.

**Comment by m1n1m4l** [comment]
But '-' is in the allowed char regex:
ALLOWED_CHARS_PATTERN = re.compile(r'[^-a-z0-9]+')
ALLOWED_CHARS_PATTERN_WITH_UPPERCASE = re.compile(r'[^-a-zA-Z0-9]+')

So it's not logic to not keep them.

**Comment by un33k** [comment]
Yes, `-` is allowed as the default separator, which is a general form of a slug in URLS . However due to requests, the separator overwrite was added ... and at the end of the function, the optional separator will swap the default one.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

Literal-hyphen preservation remains unsupported for compatibility. Modern separator length budgeting is a separate improvement, not a fix for literal dash preservation.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
