### ISSUE TITLE
We cannot replace '-' before replacing ' ' by '-'

### ISSUE THREAD

**Issue by somenxavier** [un33k/python-slugify#94]
I get something like this

```
slugify.slugify('Hola això és - * - = +', replacements=[['-','menys']])
'holamenysaixomenysesmenysmenysmenysmenys'
```

While I expect something like this:
```
hola-aixo-es-menys-menys
```
because I want to replace '-' by 'menys' before replacing ' ' by '-'

**Comment by un33k** [comment]
@somenxavier Pls look at the default separator parameter.  `replacements` is performed after `separator`.  It doesn't matter which one is performed first, someone will be out there that would requires the reverse order.  So, I do recommend that you combine the parameters to achieve what you need the final string to be. You can also pre/post `search & replace` to futher prune your string.

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

Explicit pre-only replacement stages address the replacement-order use case while retaining the historical two-pass default.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
