### ISSUE TITLE
[fyi] stubs for python-slugify were submitted to typeshed

### ISSUE THREAD

**Issue by hauntsaninja** [un33k/python-slugify#95]
Type stubs for this library were submitted to typeshed in https://github.com/python/typeshed/pull/4429

You don't need to take any action, but:
a) If you wish to include type stubs as part of your package, we're happy to transfer them to this repo (or potentially aid with the addition of inline types)
b) If you want us to remove the stubs from typeshed, we will!

**Comment by un33k** [comment]
Yeah, it is time to `type` everything up ... I'll look forward to your PR & thank you.
