### ISSUE TITLE
publish pre-build wheels (manylinux)

### ISSUE THREAD

**Issue by ssbarnea** [un33k/python-slugify#96]
Installing python-slugify can takes ages as due to recompilation. It would prove very useful if pre-build wheels would also be published to pypi.

As a note, github actions can be used to produce binaries for almost any platform, including arm64. There is no need to cover all platforms, including linux and macos x64 would probably already cover most use case. Once the project has

I am not yet sure if that is only a performance issue but even after 10mins, pip is still stuck trying to build it.
```
Processing /Users/ssbarnea/Library/Caches/pip/wheels/11/94/81/312969455540cb0e6a773e5d68a73c14128bfdfd4a7969bb4f/python_slugify-4.0.0-py2.py3-none-any.whl
```
![](https://sbarnea.com/ss/Screen-Shot-2020-10-16-09-32-04.03.png)

**Comment by un33k** [comment]
@ssbarnea Be great if you can push a PR. Thx

**Comment by thijstriemstra** [comment]
Was having the same issue. Since the correct info in `setup.cfg` is already there, it's a matter of publishing the wheel correctly, no PR needed.

```
python setup.py bdist_wheel
```

See https://packaging.python.org/guides/distributing-packages-using-setuptools/#wheels @un33k

**Comment by un33k** [comment]
I was hoping for a publish.sh where it would run ...

```
python setup.py publish && python setup.py bdist_wheel
```

Manually is ok too ...

**Comment by thijstriemstra** [comment]
make sure the wheel contains everything you want, or you might need an `MANIFEST.in` file..

**Comment by un33k** [comment]
Back to my original call for a PR ...

**Comment by un33k** [comment]
This is **Dojo**, posting a maintainer-authorized follow-up linking this issue to https://github.com/un33k/python-slugify/pull/191.

Pure-Python wheel build and artifact checks are provided. This does not announce publication; platform-specific manylinux machinery is unnecessary for the pure-Python wheel.

The default algorithm remains legacy; improved output rules are opt-in. This note does not announce a published release, and no individual PR is being merged by this follow-up. Thank you for the contribution and discussion.

🚀 Generated with [Dojo](https://heydojo.ai) ⛩️
